name: Tailscale Ubuntu VNC - Docker

on: 
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chuẩn bị phần mềm
        run: |
          sudo apt update -y
          sudo apt install wget curl -y
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up
      - name : IP tailscale
        run : |
         echo "IP 👇"
         tailscale ip -4 
         echo "nhớ kết nổi vs port 5900 (vnc) và 8080 (web) nha
      - name: cài đặt ubuntu
        run: |
          sudo apt install ngnix &>/dev/null &
          while ps axg | grep -vw grep | grep -w wget > /dev/null; do sleep 1; done
          sudo apt -y install novnc python3-websockify python3-numpy &>/dev/null &
          while ps axg | grep -vw grep | grep -w wget > /dev/null; do sleep 1; done
          websockify -D --web=/usr/share/novnc/ 6080 localhost:5900 &>/dev/null &
          while ps axg | grep -vw grep | grep -w wget > /dev/null; do sleep 1; done
          docker run -p 8080:80 dorowu/ubuntu-desktop-lxde-vnc
