name: Tailscale Windows 8 No Pro

on: 
  workflow_dispatch:
    
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chuẩn bị phần mềm
        run: |
          sudo apt update -y
          sudo apt install wget curl -y
          sudo apt install p7zip
          sudo apt install -y qemu-kvm cpulimit python3-pip
          wget -O start.sh https://github.com/Snhvn/Windocker/raw/refs/heads/main/b.sh
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up
      - name: cài win và khởi chạy
        run: |
          sudo chmod 666 /dev/kvm
          echo "Đợi khoảng 3 phút để tải xong"
          sudo wget -O /mnt/win8.py https://archive.org/download/windows-7-6469.7znbabtermux/Windows%207%206469.7z &>/dev/null &
          while ps axg | grep -vw grep | grep -w wget > /dev/null; do sleep 1; done
          sudo pip install gdown
          sudo python3 "/mnt/win8.py"
          echo "Đang giải nén tất cả các file .7z trong /mnt..."
          sudo 7z x mnt/a.7z && sudo rm -rf mnt/a.7z
          echo "Đang khởi chạy máy ảo..."
          echo "Đã khởi động VM thành công và mở cổng 5900"
          tailscale ip -4
          sudo sh start.sh
          while ps axg | grep -vw grep | grep -w qemu-system-x86_64 > /dev/null; do sleep 1; done
          while ps axg | grep -vw grep | grep -w kvm > /dev/null; do sleep 1; done
