name: Tailscale Ubuntu Spice

on: 
  workflow_dispatch:
    
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chuẩn bị phần mềm
        run: |
          sudo apt update -y
          sudo apt install wget curl -y
          sudo apt install -y qemu-kvm unzip cpulimit python3-pip
          sudo apt -y install novnc python3-websockify python3-numpy
          wget -O start.sh https://github.com/Snhvn/Tong-hop-windows/raw/refs/heads/main/spice.sh
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up
      - name: cài win và khởi chạy
        run: |
          sudo chmod 666 /dev/kvm
          echo "Đợi khoảng 14 phút để tải xong"
          sudo wget -O /mnt/ubuntu.py https://github.com/Snhvn/Tong-hop-windows/raw/refs/heads/main/ubuntu.py &>/dev/null &
          while ps axg | grep -vw grep | grep -w wget > /dev/null; do sleep 1; done
          sudo pip install gdown
          sudo python3 "/mnt/ubuntu.py"
          echo "Đang khởi chạy máy ảo..."
          echo "Đã khởi động VM thành công và mở cổng 5900(vnc),5924(spice)"
          websockify -D --web=/usr/share/novnc/ 6080 localhost:5900
          tailscale ip -4
          sudo sh start.sh
          while ps axg | grep -vw grep | grep -w qemu-system-x86_64 > /dev/null; do sleep 1; done
          while ps axg | grep -vw grep | grep -w kvm > /dev/null; do sleep 1; done
